trigger:
- master

pool:
  vmImage: ubuntu-latest
  
steps:
- task: Docker@2
  displayName: 'Build NodeJS Image'
  inputs:
    command: 'build'
    Dockerfile: '**/Dockerfile'
    arguments: '-t appimage1:latest'
    
- task: trivy@1
  inputs:
    version: 'latest'
    image: 'appimage1'
    exitCode: '0'

