name: Image Build and Scan
on:
  push:
    branches: [ main ]
jobs:
  build-docker-image:
    name: Build docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Build Docker Image
      run: docker build -t nodejs:latest .

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@0.20.0
      with:
        image-ref: nodejs:latest
        format: 'table'
        exit-code: '1'
        ignore-unfixed: false
        vuln-type: 'os'
        scanners: 'vuln'
        severity: "HIGH,CRITICAL"
